In [8]:
import pandas as pd
import sys
import os
projeto_dir = os.path.abspath('..')
sys.path.append(projeto_dir)

from api.ibge_api_consumer import IbgeApiConsumer
from config.bussines_rules import SEGMENTOS , CANAIS

df = pd.DataFrame()

arquivos =['dt1.csv','dt2.csv','dt3.csv','dt4.csv']


for csv in arquivos:
    df1 = pd.read_csv(csv,sep=';')
    df = pd.concat([df,df1],axis=0)

a = df.loc[df['cnae_principal'] == 4711301]


def create_collumn_cidade():
    lista_municipios_df = list(df['municipio-id'].unique())
    api = IbgeApiConsumer()
    municipio_id_name = {}

    for municipio in lista_municipios_df:
        result = api.get_municipios(municipio)
        municipio_id_name[str(municipio)] = result['nome']
        
    def get_name_municipio(id):
        name = municipio_id_name[str(id)]
        return name

    df['cidade'] = df['municipio-id'].apply(get_name_municipio)
    return df

def get_name_by_identificador(id:str or int,identificador:dict):
    for tupla in identificador.items():
        if(id in tupla[1]):
            return tupla[0]
    return 'OUTROS' 

 ## caso nao houvesse esse retorno 'OUTROS' poderia ser tratado depois dessa forma df['segmento'].fillna('OUTROS',inplace=True)

def create_collumn_segmento():
    def get_name_segmento(id_cnae):
        return get_name_by_identificador(int(id_cnae),SEGMENTOS)
            
    df['segmento'] = df['cnae_principal'].apply(get_name_segmento)
    return df
  
def create_collumn_canal():
    def get_name_canal(segmento):
        return get_name_by_identificador(segmento,CANAIS)

    df['canal'] = df['segmento'].apply(get_name_canal)
    return df

def update_dataframe():
    create_collumn_cidade()
    create_collumn_segmento()
    create_collumn_canal()
    
update_dataframe()

bob esponjoaskosanjsa
bob esponjoaskosanjsa
bob esponjoaskosanjsa
bob esponjoaskosanjsa
bob esponjoaskosanjsa
bob esponjoaskosanjsa

In [ ]:
df_cidade = df.loc[(df['segmento'] == 'PET SHOP')]


cidade_mais_estabelcimento = df_cidade['cidade'].value_counts().idxmax()

df_cidade = df_cidade[df_cidade['cidade'] == cidade_mais_estabelcimento]

bairros_contagem = df_cidade['bairro'].value_counts().reset_index()

bairros_contagem

                     bairro  count
0                 ESPLANADA     29
1                    CENTRO     19
2                BELA VISTA     18
3                  CRUZEIRO     17
4   NOSSA SENHORA DE FATIMA     16
..                      ...    ...
63       NOSSA SRA. LOURDES      1
64                 SAO CIRO      1
65                 LINHA 40      1
66                 MARILAND      1
67            FAZENDA SOUZA      1

[68 rows x 2 columns]

In [13]:
aa = df.loc[df['segmento'] == 'HIPERMERCADO']
aa['cidade']

154    Caxias do Sul
343    Caxias do Sul
606    Caxias do Sul
661    Caxias do Sul
870    Caxias do Sul
999    Caxias do Sul
Name: cidade, dtype: object